import { Wallet } from '../type/wallet';

export const data: Wallet[] = [
  {
    _id: '1',
    image:
      'https://cdn.britannica.com/33/4833-004-828A9A84/Flag-United-States-of-America.jpg',
    currency: 'USD',
    name: 'US Dollar',
    type: 'Fiat',
    balance: 1000,
    convertedBalance: 1000,
    network: ['Bitcoin', 'Ethereum'],
    address: '',
  },
  {
    _id: '3',
    image:
      'https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/2560px-Flag_of_the_United_Kingdom.svg.png',
    currency: 'GBP',
    name: 'British Pound',
    type: 'Fiat',
    balance: 750,
    convertedBalance: 950,
    network: [],
    address: '',
  },
  {
    _id: '4',
    image:
      'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png',
    currency: 'JPY',
    name: 'Japanese Yen',
    type: 'Fiat',
    balance: 120000,
    convertedBalance: 1100,
    network: [],
    address: '',
  },
  {
    _id: '5',
    image:
      'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png',
    currency: 'EUR',
    name: 'Euro',
    type: 'Fiat',
    balance: 850,
    convertedBalance: 900,
    network: [],
    address: '',
  },
  {
    _id: '6',
    image:
      'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png',
    currency: 'AUD',
    name: 'Australian Dollar',
    type: 'Fiat',
    balance: 500,
    convertedBalance: 750,
    network: [],
    address: '',
  },
  {
    _id: '7',
    image:
      'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png',
    currency: 'CAD',
    name: 'Canadian Dollar',
    type: 'Fiat',
    balance: 600,
    convertedBalance: 700,
    network: [],
    address: '',
  },
  {
    _id: '8',
    image:
      'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png',
    currency: 'CNY',
    name: 'Chinese Yuan',
    type: 'Fiat',
    balance: 4500,
    convertedBalance: 800,
    network: [],
    address: '',
  },
  {
    _id: '9',
    image:
      'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png',
    currency: 'INR',
    name: 'Indian Rupee',
    type: 'Fiat',
    balance: 30000,
    convertedBalance: 950,
    network: [],
    address: '',
  },
  {
    _id: '10',
    image:
      'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png',
    currency: 'BRL',
    name: 'Brazilian Real',
    type: 'Fiat',
    balance: 1200,
    convertedBalance: 1000,
    network: [],
    address: '',
  },
  {
    _id: '11',
    image:
      'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png',
    currency: 'CHF',
    name: 'Swiss Franc',
    type: 'Fiat',
    balance: 800,
    convertedBalance: 850,
    network: [],
    address: '',
  },
  {
    _id: '12',
    image:
      'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png',
    currency: 'MXN',
    name: 'Mexican Peso',
    type: 'Fiat',
    balance: 2500,
    convertedBalance: 1050,
    network: [],
    address: '',
  },
  {
    _id: '13',
    image:
      'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png',
    currency: 'RUB',
    name: 'Russian Ruble',
    type: 'Fiat',
    balance: 15000,
    convertedBalance: 1100,
    network: [],
    address: '',
  },
  {
    _id: '14',
    image:
      'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png',
    currency: 'KRW',
    name: 'South Korean Won',
    type: 'Fiat',
    balance: 70000,
    convertedBalance: 900,
    network: [],
    address: '',
  },
  {
    _id: '15',
    image:
      'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png',
    currency: 'SEK',
    name: 'Swedish Krona',
    type: 'Fiat',
    balance: 900,
    convertedBalance: 950,
    network: [],
    address: '',
  },
];
